version: '3'
services:
  db:
    image: mysql:5.6.50
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: db.env
volumes:
  mysql-data:
    driver: local